version: '3.8'
services:
  app:
    image: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
